hm_woman_category = [
    {"category": "상의", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/tops.html"},
    {"category": "상의", "url": "https://www2.hm.com/ko_kr/ladies/sale/tops.html"},
    {"category": "드레스", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/dresses.html"},
    {"category": "드레스", "url": "https://www2.hm.com/ko_kr/ladies/sale/dresses.html"},
    {"category": "팬츠", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/trousers.html"},
    {"category": "팬츠", "url": "https://www2.hm.com/ko_kr/ladies/sale/trousers.html"},
    {"category": "셔츠/블라우스", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/shirts-and-blouses.html"},
    {"category": "셔츠/블라우스", "url": "https://www2.hm.com/ko_kr/ladies/sale/shirtsblouses.html"},
    {"category": "스커트", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/skirts.html"},
    {"category": "스커트", "url": "https://www2.hm.com/ko_kr/ladies/sale/skirts.html"},
    {"category": "데님", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/jeans.html"},
    {"category": "데님", "url": "https://www2.hm.com/ko_kr/ladies/sale/jeans.html"},
    {"category": "가디건", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/cardigans-and-jumpers.html"},
    {"category": "가디건", "url": "https://www2.hm.com/ko_kr/ladies/sale/cardigansjumpers.html"},
    {"category": "블레이저", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/blazers-and-waistcoats.html"},
    {"category": "블레이저", "url": "https://www2.hm.com/ko_kr/ladies/sale/blazerswaistcoats.html"},
    {"category": "쇼츠", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/shorts.html"},
    {"category": "쇼츠", "url": "https://www2.hm.com/ko_kr/ladies/sale/shorts.html"},
    {"category": "재킷/코트", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/jackets-and-coats.html"},
    {"category": "재킷/코트", "url": "https://www2.hm.com/ko_kr/ladies/sale/jacketscoats.html"},
    {"category": "후드티/스웨트셔츠", "url": "https://www2.hm.com/ko_kr/ladies/shop-by-product/hoodies-sweatshirts.html"},
    {"category": "후드티/스웨트셔츠", "url": "https://www2.hm.com/ko_kr/ladies/sale/hoodies-sweatshirts.html"},
    {"category": "점프수트", "url": "https://www2.hm.com/ko_kr/ladies/sale/jumpsuits.html"},
]